name: Déploiement documentation Sphinx

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Installer Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Installer les dépendances pour la documentation
      run: pip install -r docs/requirements.txt

    - name: Générer la documentation
      run: sphinx-build -b html docs/ docs/_build/html

    - name: Déployer sur GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/_build/html
        publish_branch: gh-pages
        force_orphan: true
