# .github/workflows/doc.yaml

name: Déploiement documentation Sphinx

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Récupère le code du dépôt
    - uses: actions/checkout@v4

    # 2. Mettre en place l'environnement Python
    - name: Installer Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    # 3. Installer les dépendances
    - name: Installer les dépendances
      run: |
        pip install -r docs/requirements.txt
        pip install .

    # 4. Générer la documentation
    - name: Générer la documentation Sphinx
      run: sphinx-build -b html docs/source/ docs/_build/html

    # 5. Déployer sur la branche gh-pages
    - name: Déployer sur GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/_build/html